field.field.node.event.field_event_date:
  expected_config:
    default_value: {  }
  update_actions:
    change:
      default_value:
        -
          default_date: now
          default_date_type: now
